spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bubble
    username: root
    password: 1234

  flyway:
    user: root
    password: 1234
    clean-disabled: true
    locations: classpath:/db/migration
    url: jdbc:mysql://localhost:3306/bubble
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile



mybatis:
  mapper-locations: mybatis/mapper/**/*.xml


logging:
  level:
    root: debug