services:
  rabbitmq:
    container_name: 'rabbit'
    image: rabbitmq:management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=1234'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped


  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306